### ISSUE TITLE
Please don't force defining rules in the package.json

### ISSUE THREAD

**Issue by j0hnm4r5** [jorgegonzalez/korra#3]
Same issue as [here](https://github.com/xojs/xo/issues/330). Please allow for a `.korrarc` for rules, in addition to being able to set them in the `package.json`.

**Comment by jorgegonzalez** [comment]
Sure.

**Comment by jorgegonzalez** [comment]
I’m curious, are there any rules included in the default config that you think should be changed?

**Comment by j0hnm4r5** [comment]
Not quite sure yet; I just started using it. But I'm coming from XO and there were a few ESLint rules I had modified from that.

**Comment by azdanov** [comment]
Maybe consider default prettier rules out of the box?

Since this is an opinion, `single` vs `double` quotes: https://github.com/jorgegonzalez/korra/blob/b519ae3845a7235c7d595c503e361c77c97e81f6/eslintrc.json#L29

Later on, an end user can add what is necessary for their project.

**Comment by jorgegonzalez** [comment]
@azdanov I did originally want to leave the default Prettier rules in, but `singleQuotes` seem to be significantly more common in JS projects.

Many Prettier users have also requested that [they change this default](https://github.com/prettier/prettier/issues/4102), and I suspect they will make this change eventually.

**Comment by j0hnm4r5** [comment]
Yeah, I’m thinking the same thing. Just leave everything at the barebones defaults, and leave it to the users to change what they need. 

The community doesn’t need another rules standard; what drew me to Korra was the out-of-the-box integration of ESLint and Prettier.

**Comment by jorgegonzalez** [comment]
@j0hnm4r5 No worries.

Yeah I love XO and its devs, (and I've made some minor contributions to it), I just dislike having to install 6 other configs and plugins to get XO to work with React and TypeScript, for example, thus why I started this project.

**Comment by j0hnm4r5** [comment]
Yeah, it’s ease of use is wonderful, and it gives me everything I want. 

Next time I teach a class, I’m totally making everyone use it, and I’ll try to add it to everyone’s workflows at work as well.

**Comment by jorgegonzalez** [comment]
Added `cosmiconfig` in f1b6c5d.

**Comment by jorgegonzalez** [comment]
@j0hnm4r5 Close this issue if you consider this resolved.

**Comment by jorgegonzalez** [comment]
Actually, you can go ahead and describe this new feature in the README if you want to make a PR. I'm checking out for the night. ✌️

**Comment by jorgegonzalez** [comment]
Hey in addition to `.zoerc.json` and `.zoerc.yaml`, you can also now define your configs in `.zoerc.toml` files 🎉
