### ISSUE TITLE
Korra ignoring / fighting with user-defined rules and prettier config.

### ISSUE THREAD

**Issue by j0hnm4r5** [jorgegonzalez/korra#7]
I'm not sure if I'm doing something wrong, Korra seems to be ignoring / fighting with some of my `.prettierrc`, and any `"prettier": {}` configs done in the `package.json`.

I'm using VSCode, with the `vscode-eslint` extension. Settings are

```json
"eslint.autoFixOnSave": true,
"eslint.options": {
    "configFile": "./node_modules/korra/eslintrc.json"
}
```

as per #6 .

Korra is installed locally, not globally. Some changes to either prettier config location do not work, even after a `Reload Window`. 

Try creating a `.prettierrc` with `{ "semicolons": false }` to test. After reloading the window, the prettier rule is ignored. Then try with `{ "printWidth": 20 }`. After reloading the window, ESLint will throw `prettier/prettier` errors.

I do not have the Prettier VSCode extension enabled (when I did, `ESLint --fix` and its fix-on-save were fighting with each other; every time I saved, the quotes throughout the entire file alternated between single and double)

**Comment by jorgegonzalez** [comment]
In a `.prettierrc` it's `{ "semi": false }`. This follows the Prettier options [API](https://prettier.io/docs/en/options.html).

`"quotes": [ "error", "backtick" ],` is ignored because Prettier takes precedent.

I can't reproduce the `"prefer-const": "error"`. I just set this in a fresh repo and it works for me.

**Comment by jorgegonzalez** [comment]
`printWidth` worked because that's the exact string Prettier defines for that option.

**Comment by jorgegonzalez** [comment]
Setting the following in `package.json` is also working for me:

```json
"prettier": {
  "semi": false
}
```

**Comment by j0hnm4r5** [comment]
That did fix the semicolons issue. Oh man, I can't believe I've been doing that wrong for months.

On other repos, where I use both prettier and `"quotes": [ "error", "backtick" ]` does work, I think because Prettier doesn't care about them.

I'm definitely not getting `prefer-const` to work. You created a new repo, added `let a = 3;`, and `"prefer-const": "error"` to the rules, and you were getting an error?

**Comment by j0hnm4r5** [comment]
Oh, and `singleQuote: false` in prettier isn't changing everything to double quotes.

**Comment by jorgegonzalez** [comment]
Yep 
![image](https://user-images.githubusercontent.com/12901172/42730904-33e62524-87d0-11e8-8967-84bf3bae4c1d.png)

**Comment by jorgegonzalez** [comment]
`singleQuote: false` is indeed not working. Let me investigate.

**Comment by j0hnm4r5** [comment]
I just removed `"prettier/prettier": [ "error", { "singleQuote": true } ]` and `"prefer-const": "off"` from the `eslintrc.json` in the `korra` folder in my `node_modules` for the project, and both my quotes and const issue fixed themselves.

It seems like that file is taking precedence.

**Comment by j0hnm4r5** [comment]
Try running it with the VSCode ESLint plugin too, just in case something is happening there.

**Comment by jorgegonzalez** [comment]
Oh I totally misunderstood you. You mean it's not working in vscode-eslint!

I'm aware of this. We need to create our own editor plugin to overcome this issue, there's no easy way for vscode-eslint to dynamically read Korra's options.

**Comment by j0hnm4r5** [comment]
And I added `"quotes": [ "error", "backtick" ]` to the node_modules `eslintrc.json` as well, and it did auto-fix all my strings to backticks.

**Comment by jorgegonzalez** [comment]
So as of this moment the CLI is the only way that Korra works as intended.

**Comment by j0hnm4r5** [comment]
When you say dynamically, do you mean without having to reload the window every time a change is made to a config, or to allow rules in the `package.json` to work?

**Comment by j0hnm4r5** [comment]
I think something is off, though. The fact that rules are working when I modify them in `node_modules`, but not in `package.json`, doesn't have anything to do with vscode-eslint, does it? Changes to the `node_modules` config are working with vscode-eslint's fix-on-save.

**Comment by jorgegonzalez** [comment]
I mean without making changes directly to `node_modules/korra/eslintrc.json`. `vscode-eslint` will always run ESLint based on that config. It cannot be aware of options set in `package.json#korra` or a `.korrarc` file.

**Comment by jorgegonzalez** [comment]
> I think something is off, though. The fact that rules are working when I modify them in node_modules, but not in package.json, doesn't have anything to do with vscode-eslint, does it?

`vscode-eslint` has no way of looking in `package.json#korra`. The only way to integrate VSCode and Korra is a custom extension. The instructions in the README are supposed to be a temporary workaround.
